//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vahti.Mobile.Forms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vahti.Mobile.Forms.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string App_TabSummaryTitle {
            get {
                return ResourceManager.GetString("App_TabSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vahti.
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string ColorTheme_Gray {
            get {
                return ResourceManager.GetString("ColorTheme_Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string ColorTheme_Light {
            get {
                return ResourceManager.GetString("ColorTheme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging.
        /// </summary>
        internal static string Converter_SecondsToLastCharged_Charging {
            get {
                return ResourceManager.GetString("Converter_SecondsToLastCharged_Charging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mowing ({0} min).
        /// </summary>
        internal static string Converter_SecondsToLastCharged_Mowing {
            get {
                return ResourceManager.GetString("Converter_SecondsToLastCharged_Mowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Converter_SecondsToLastCharged_NoInfo {
            get {
                return ResourceManager.GetString("Converter_SecondsToLastCharged_NoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details_Title {
            get {
                return ResourceManager.GetString("Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity (%).
        /// </summary>
        internal static string Graph_HumidityGraphTitle {
            get {
                return ResourceManager.GetString("Graph_HumidityGraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature (°C).
        /// </summary>
        internal static string Graph_TemperatureGraphTitle {
            get {
                return ResourceManager.GetString("Graph_TemperatureGraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string Graph_Title {
            get {
                return ResourceManager.GetString("Graph_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem when accessing the database. Please check that URL defined in App.config is valid: {0}. To use fake data instead, select &quot;DebugMock&quot; build configuration.
        /// </summary>
        internal static string Locations_DatabaseProblem {
            get {
                return ResourceManager.GetString("Locations_DatabaseProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data was last updated on {0}.
        /// </summary>
        internal static string Locations_LastUpdatedText {
            get {
                return ResourceManager.GetString("Locations_LastUpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Locations_UpdateButtonText {
            get {
                return ResourceManager.GetString("Locations_UpdateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud database secret:.
        /// </summary>
        internal static string Options_CloudDatabaseSecretLabel {
            get {
                return ResourceManager.GetString("Options_CloudDatabaseSecretLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud database URL:.
        /// </summary>
        internal static string Options_CloudDatabaseUrlLabel {
            get {
                return ResourceManager.GetString("Options_CloudDatabaseUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud database URL has to be specified.
        /// </summary>
        internal static string Options_CloudDatabaseUrlMissingLabel {
            get {
                return ResourceManager.GetString("Options_CloudDatabaseUrlMissingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color theme:.
        /// </summary>
        internal static string Options_ColorThemeLabel {
            get {
                return ResourceManager.GetString("Options_ColorThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Options_General_Title {
            get {
                return ResourceManager.GetString("Options_General_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose items to show in summary view:.
        /// </summary>
        internal static string Options_Summary_Description {
            get {
                return ResourceManager.GetString("Options_Summary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Options_Summary_Title {
            get {
                return ResourceManager.GetString("Options_Summary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options_Title {
            get {
                return ResourceManager.GetString("Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose items (3) to show in Android widget:.
        /// </summary>
        internal static string Options_Widget_Description {
            get {
                return ResourceManager.GetString("Options_Widget_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget.
        /// </summary>
        internal static string Options_Widget_Title {
            get {
                return ResourceManager.GetString("Options_Widget_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration (X).
        /// </summary>
        internal static string SensorClass_accelerationX {
            get {
                return ResourceManager.GetString("SensorClass_accelerationX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration (Y).
        /// </summary>
        internal static string SensorClass_accelerationY {
            get {
                return ResourceManager.GetString("SensorClass_accelerationY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceleration (Z).
        /// </summary>
        internal static string SensorClass_accelerationZ {
            get {
                return ResourceManager.GetString("SensorClass_accelerationZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery voltage.
        /// </summary>
        internal static string SensorClass_batteryVoltage {
            get {
                return ResourceManager.GetString("SensorClass_batteryVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        internal static string SensorClass_humidity {
            get {
                return ResourceManager.GetString("SensorClass_humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last charged.
        /// </summary>
        internal static string SensorClass_lastCharged {
            get {
                return ResourceManager.GetString("SensorClass_lastCharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement counter.
        /// </summary>
        internal static string SensorClass_movementCounter {
            get {
                return ResourceManager.GetString("SensorClass_movementCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air pressure.
        /// </summary>
        internal static string SensorClass_pressure {
            get {
                return ResourceManager.GetString("SensorClass_pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string SensorClass_temperature {
            get {
                return ResourceManager.GetString("SensorClass_temperature", resourceCulture);
            }
        }
    }
}
