#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Vahti.Mobile.Droid.Resource", IsApplication=true)]

namespace Vahti.Mobile.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int black_transparent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorAccent = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimary = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int colorPrimaryDark = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int forestGreen = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int gray = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int launcher_background = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int listViewSelectedGray = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int listViewSelectedGreen = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int listViewSelectedLight = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int white = 2130771978;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int bg_splash = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int ic_launcher_lighthouse = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int ic_menu_info = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int ic_menu_list = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int ic_menu_settings = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int ic_stat_lighthouse = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int ic_toolbar_refresh = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int splash_screen = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int header1 = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int header2 = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int header3 = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int message = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int sliding_tabs = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int toolbar = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int updated = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int value1 = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int value2 = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int value3 = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int widget = 2130903050;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int widget_loading = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int widget_sensors = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int widget_loading = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int widget_name = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int AppCompatDialogStyle = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int GrayTheme = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int GreenTheme = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int LightTheme = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int MainTheme_Dark = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int MainTheme_Light = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int Splash = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int Widget = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int WidgetBackground = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int Widget_Header = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int Widget_Value = 2131099658;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F070000
			public const int widget_sensor = 2131165184;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
